controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

choixInscription:
    path : /choixinscription
    controller : App\Controller\IndexController::choix


adminAjouter:
    path : /admin/Register
    controller: App\Controller\AdminController::ajouterAdmin

adminLister:
    path : /admin/listerAdmin
    controller: App\Controller\AdminController::listerAdmin

adminSupprimer:
    path : /admin/supprimer/{id}
    controller: App\Controller\AdminController::supprimerAdmin


accueilIndex:
    path : /
    controller: App\Controller\IndexController::index

formReservation:
    path : /reservation
    controller : App\Controller\IndexController::formReservation

showFormReservation:
    path : /reservationShow
    controller : App\Controller\IndexController::showFormReservation

detailReservation:
    path : /reservationDetail
    controller : App\Controller\IndexController::modalDetail

modalEspace:
    path : /modalEspace/{idCarrousel}/{idEspace}
    controller : App\Controller\IndexController::modalEspace

annuaireLister:
    path : /user/annuaire
    controller: App\Controller\AnnuaireController::lister



independantConsulter:
    path: /independant/consulter/{id}
    controller: App\Controller\IndependantController::consulterIndependant

independantLister:
    path: /admin/independant/lister
    controller: App\Controller\IndependantController::listerIndependant

independantAjouter:
    path: /public/ajouterinde
    controller: App\Controller\IndependantController::ajouterIndependant

independantModifier:
    path: /independant/modifier/{id}
    controller: App\Controller\IndependantController::modifierIndependant

independantSupprimer:
    path: /admin/independant/supprimer/{id}
    controller: App\Controller\IndependantController::supprimerIndependant

independant_sendmail:
    path: /independant/consultersend/{id}
    controller: App\Controller\IndependantController::sendmailIndependant



independantModifierInfo:
    path: /independant/modifierinfo/{id}
    controller: App\Controller\IndependantController::ModifInfoIndependant

independantModifierPhotoDeProfil:
    path: /independant/modifierPdp/{id}
    controller: App\Controller\IndependantController::ModifPhotoDeProfilIndependant

independantModifierTag:
    path: /independant/modifierTag/{id}
    controller: App\Controller\IndependantController::ModifTagIndependant

independantCréerPortfolio:
    path: /independant/ajouterPortfolio/{id}
    controller: App\Controller\IndependantController::AddPortfolioIndependant

independantModifierPortfolio:
    path: /independant/modifierPortfolio/{id}
    controller: App\Controller\IndependantController::ModifPortfolioIndependant

independantSupprimerPortfolio:
    path: /independant/supprimerPortfolio/{id}
    controller: App\Controller\IndependantController::SupprimerPortfolioIndependant



independantAjouterVideo:
    path: /independant/ajouterVideo/{id}
    controller: App\Controller\IndependantController::AjouterVideoIndependant

independantSupprimerVideo:
    path: /independant/supprimerVideo/{id}
    controller: App\Controller\IndependantController::SupprimerVideoIndependant

independantModifierVideo:
    path: /independant/modifierVideo/{id}
    controller: App\Controller\IndependantController::modifierVideoIndependant

independantListerVideo:
    path: /independant/listerVideo/{id}
    controller: App\Controller\IndependantController::listerVideoIndependant


statutConsulter:
    path: /admin/statut/consulter/{id}
    controller: App\Controller\StatutController::consulterStatut

statutLister:
    path: /admin/statut/lister
    controller: App\Controller\StatutController::listerStatut

statutAjouter:
    path: /admin/statut/ajouter
    controller: App\Controller\StatutController::ajouterStatut

statutModifier:
    path: /admin/statut/modifier/{id}
    controller: App\Controller\StatutController::modifierStatut

statutSupprimer:
    path: /admin/statut/supprimer/{id}
    controller: App\Controller\StatutController::supprimerStatut



metierConsulter:
    path: /admin/metier/consulter/{id}
    controller: App\Controller\MetierController::consulterMetier

metierLister:
    path: /admin/metier/lister
    controller: App\Controller\MetierController::listerMetier

metierAjouter:
    path: /admin/metier/ajouter
    controller: App\Controller\MetierController::ajouterMetier

metierModifier:
    path: /admin/metier/modifier/{id}
    controller: App\Controller\MetierController::modifierMetier

metierSupprimer:
    path: /admin/metier/supprimer/{id}
    controller: App\Controller\MetierController::supprimerMetier



entrepriseConsulter:
    path: /entreprise/consulter/{id}
    controller: App\Controller\EntrepriseController::consulterEntreprise

entrepriseLister:
    path: /admin/entreprise/lister
    controller: App\Controller\EntrepriseController::listerEntreprise

entrepriseAjouter:
    path: /public/ajouterentreprise
    controller: App\Controller\EntrepriseController::ajouterEntreprise

entrepriseModifier:
    path: /entreprise/modifier/{id}
    controller: App\Controller\EntrepriseController::modifierEntreprise

entrepriseSupprimer:
    path: /admin/entreprise/supprimer/{id}
    controller: App\Controller\EntrepriseController::supprimerEntreprise



secteuractiviteConsulter:
    path: /admin/secteuractivite/consulter/{id}
    controller: App\Controller\SecteurActiviteController::consulterSecteurActivite

secteuractiviteLister:
    path: /admin/secteuractivite/lister
    controller: App\Controller\SecteurActiviteController::listerSecteurActivite

secteuractiviteAjouter:
    path: /admin/secteuractivite/ajouter
    controller: App\Controller\SecteurActiviteController::ajouterSecteurActivite

secteuractiviteModifier:
    path: /admin/secteuractivite/modifier/{id}
    controller: App\Controller\SecteurActiviteController::modifierSecteurActivite

secteuractiviteSupprimer:
    path: /admin/secteuractivite/supprimer/{id}
    controller: App\Controller\SecteurActiviteController::supprimerSecteurActivite



tagConsulter:
    path: /admin/tag/consulter/{id}
    controller: App\Controller\TagController::consulterTag

tagLister:
    path: /admin/tag/lister
    controller: App\Controller\TagController::listerTag

tagAjouter:
    path: /admin/tag/ajouter
    controller: App\Controller\TagController::ajouterTag

tagModifier:
    path: /admin/tag/modifier/{id}
    controller: App\Controller\TagController::modifierTag

tagSupprimer:
    path: /admin/tag/supprimer/{id}
    controller: App\Controller\TagController::supprimerTag
    
    

annuaireControl:
    path: /admin/annuaire
    controller: App\Controller\AdminController::annuaireControl

adminAjoutReservation:
    path: /admin/reservationAjout
    controller: App\Controller\AdminController::adminAjoutReservation

adminReservation:
    path: /admin/reservation
    controller: App\Controller\AdminController::adminReservation

adminAnnuleReservation:
    path: /admin/reservation/cancel
    controller: App\Controller\AdminController::adminAnnuleReservation

adminEspace:
    path: /admin/espace
    controller: App\Controller\AdminController::adminEspace

adminEspacePrix:
    path: /admin/espacePrix/{id}
    controller: App\Controller\AdminController::adminEspacePrix

adminEspacePrixAjouter:
    path: /admin/espacePrixAjouter/{id}
    controller: App\Controller\AdminController::adminEspacePrixAdd

adminEspaceModif:
    path: /admin/espace/{id}
    controller: App\Controller\AdminController::adminEspaceModif

adminEspaceCarrousel:
    path: /admin/espaceCarrousel/liste/{id}
    controller: App\Controller\AdminController::adminEspaceCarrousel

adminEspaceCarrouselDel:
    path: /admin/espaceCarrousel/del/{id}
    controller: App\Controller\AdminController::adminEspaceCarrouselDel

adminEspaceCarrouselAdd:
    path: /admin/espaceCarrousel/add/{id}
    controller: App\Controller\AdminController::adminEspaceCarrouselAdd

adminEspaceSupprimer:
    path : /admin/espace/supprimer/{id}
    controller: App\Controller\AdminController::adminEspaceSupprimer

adminEspaceAjouter:
    path : /admin/espaceajouter
    controller: App\Controller\AdminController::adminEspaceAjouter

delIndependantAnnuaire:
    path: /admin/annuaire/{id}
    controller: App\Controller\AdminController::delIndependantAnnuaire

newmemberLister:
    path: /admin/newmember
    controller: App\Controller\AdminController::listerNewMember

newmemberConfirmed:
    path: /admin/confirmed/{id}
    controller: App\Controller\AdminController::confirmerNewMember

newmemberRefuser:
    path: /admin/supprimer/{id}
    controller: App\Controller\AdminController::refuserNewMember

