controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

choixInscription:
    path : /choixinscription
    controller : App\Controller\IndexController::choix


accueilIndex:
    path : /
    controller: App\Controller\IndexController::index

membreLister:
    path : /annuaire
    controller: App\Controller\MembreController::index



independantConsulter:
    path: /independant/consulter/{id}
    controller: App\Controller\IndependantController::consulterIndependant

independantLister:
    path: /independant/lister
    controller: App\Controller\IndependantController::listerIndependant

independantAjouter:
    path: /independant/ajouter
    controller: App\Controller\IndependantController::ajouterIndependant

independantModifier:
    path: /independant/modifier/{id}
    controller: App\Controller\IndependantController::modifierIndependant

independantSupprimer:
    path: /independant/supprimer/{id}
    controller: App\Controller\IndependantController::supprimerIndependant

independant_sendmail:
    path: /independant/consulter/{id}/send
    controller: App\Controller\IndependantController::sendmailIndependant


statutConsulter:
    path: /statut/consulter/{id}
    controller: App\Controller\StatutController::consulterStatut

statutLister:
    path: /statut/lister
    controller: App\Controller\StatutController::listerStatut

statutAjouter:
    path: /statut/ajouter
    controller: App\Controller\StatutController::ajouterStatut

statutModifier:
    path: /statut/modifier/{id}
    controller: App\Controller\StatutController::modifierStatut

statutSupprimer:
    path: /statut/supprimer/{id}
    controller: App\Controller\StatutController::supprimerStatut



metierConsulter:
    path: /metier/consulter/{id}
    controller: App\Controller\MetierController::consulterMetier

metierLister:
    path: /metier/lister
    controller: App\Controller\MetierController::listerMetier

metierAjouter:
    path: /metier/ajouter
    controller: App\Controller\MetierController::ajouterMetier

metierModifier:
    path: /metier/modifier/{id}
    controller: App\Controller\MetierController::modifierMetier

metierSupprimer:
    path: /metier/supprimer/{id}
    controller: App\Controller\MetierController::supprimerMetier



entrepriseConsulter:
    path: /entreprise/consulter/{id}
    controller: App\Controller\EntrepriseController::consulterEntreprise

entrepriseLister:
    path: /entreprise/lister
    controller: App\Controller\EntrepriseController::listerEntreprise

entrepriseAjouter:
    path: /entreprise/ajouter
    controller: App\Controller\EntrepriseController::ajouterEntreprise

entrepriseModifier:
    path: /entreprise/modifier/{id}
    controller: App\Controller\EntrepriseController::modifierEntreprise

entrepriseSupprimer:
    path: /entreprise/supprimer/{id}
    controller: App\Controller\EntrepriseController::supprimerEntreprise



secteuractiviteConsulter:
    path: /secteuractivite/consulter/{id}
    controller: App\Controller\SecteurActiviteController::consulterSecteurActivite

secteuractiviteLister:
    path: /secteuractivite/lister
    controller: App\Controller\SecteurActiviteController::listerSecteurActivite

secteuractiviteAjouter:
    path: /secteuractivite/ajouter
    controller: App\Controller\SecteurActiviteController::ajouterSecteurActivite

secteuractiviteModifier:
    path: /secteuractivite/modifier/{id}
    controller: App\Controller\SecteurActiviteController::modifierSecteurActivite

secteuractiviteSupprimer:
    path: /secteuractivite/supprimer/{id}
    controller: App\Controller\SecteurActiviteController::supprimerSecteurActivite



tagConsulter:
    path: /tag/consulter/{id}
    controller: App\Controller\TagController::consulterTag

tagLister:
    path: /tag/lister
    controller: App\Controller\TagController::listerTag

tagAjouter:
    path: /tag/ajouter
    controller: App\Controller\TagController::ajouterTag

tagModifier:
    path: /tag/modifier/{id}
    controller: App\Controller\TagController::modifierTag

tagSupprimer:
    path: /tag/supprimer/{id}
    controller: App\Controller\TagController::supprimerTag



